export const GETJOBS="GETJOBS"
export const GETJOBDETAILS="GETJOBDETAILS";
export const SETJOBTYPE="SETJOBTYPE";
export const SETJOBLOCATION="SETJOBLOCATION";
export const SETJOBTITLE="SETJOBTITLE";
export const RESETSEARCH="RESETSEARCH"

