export const GETJOBS="GETJOBS"
export const GETJOBDETAILS="GETJOBDETAILS";
export const SETJOBTYPE="SETJOBTYPE";
export const SETJOBLOCATION="SETJOBLOCATION";
export const SETJOBTITLE="SETJOBTITLE";
export const RESETSEARCH="RESETSEARCH";
export const INCREMENTCOUNT="INCREMENTCOUNT";
export const RESETPAGE="RESETPAGE";
export const SETDARKTHEME="SETDARKTHEME"

